### PR TITLE
add mit license

### PR DESCRIPTION
**Pull request by lrvick**

### CODE REVIEW

**Comment by KellerFuchs** [comment]
@lrvick Not sure why you want me to ACK that given that I haven't written any of the code the license would be applied to?

As a nitpick, the ISC license is equivalent, and even simpler (largely because it was written after the Berne Convention)

**Comment by lrvick** [comment]
@benharri Feel free to sign/merge when you get a chance

**Comment by KellerFuchs** [comment]
@lrvick FWIW, I don't know of a single place that disapproves of ISC and approves of the MIT/Expat license, but I don't think it's worth arguing over either.

**Comment by lrvick** [comment]
@KellerFuchs Any idea why travis is failing here? I restarted it multiple times

**Pull request merged**
